# Generated by Django 4.2.6 on 2024-04-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_userinfo_resume_team_emailconfirm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='rating',
        ),
        migrations.AddField(
            model_name='team',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
