# Generated by Django 4.2.6 on 2024-04-20 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_userinfo_rating_team_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.userinfo'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
