# Generated by Django 4.2.6 on 2024-04-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_question_email_alter_question_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='complexity',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='stack',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='about',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
