# Generated by Django 4.2.6 on 2024-04-20 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_userinfo_complexity_remove_userinfo_direction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0)),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_team_ratings', to=settings.AUTH_USER_MODEL)),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_team_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('from_team', 'to_team')},
            },
        ),
    ]
