# Generated by Django 4.2.6 on 2024-04-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_teamrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamrating',
            old_name='rating',
            new_name='design',
        ),
        migrations.AddField(
            model_name='teamrating',
            name='implementation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='teamrating',
            name='layout',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='teamrating',
            name='usability',
            field=models.FloatField(default=0),
        ),
    ]
