# Generated by Django 4.2.6 on 2024-04-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_rating_teamrating_design_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamrating',
            name='design',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='teamrating',
            name='implementation',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='teamrating',
            name='layout',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='teamrating',
            name='usability',
            field=models.FloatField(),
        ),
    ]
