# Generated by Django 4.2.6 on 2024-04-20 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_teamrating_design_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='team_name',
        ),
    ]
